# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prize_pb2 as prize__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in prize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelPrizeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLaureatesByCategoryAndYearRange = channel.unary_unary(
                '/NobelPrizeService/GetLaureatesByCategoryAndYearRange',
                request_serializer=prize__pb2.CategoryYearRequest.SerializeToString,
                response_deserializer=prize__pb2.LaureatesResponse.FromString,
                _registered_method=True)
        self.GetLaureatesByKeyword = channel.unary_unary(
                '/NobelPrizeService/GetLaureatesByKeyword',
                request_serializer=prize__pb2.KeywordRequest.SerializeToString,
                response_deserializer=prize__pb2.LaureatesResponse.FromString,
                _registered_method=True)
        self.GetLaureateByName = channel.unary_unary(
                '/NobelPrizeService/GetLaureateByName',
                request_serializer=prize__pb2.NameRequest.SerializeToString,
                response_deserializer=prize__pb2.LaureateDetailsResponse.FromString,
                _registered_method=True)


class NobelPrizeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLaureatesByCategoryAndYearRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureatesByKeyword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelPrizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLaureatesByCategoryAndYearRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByCategoryAndYearRange,
                    request_deserializer=prize__pb2.CategoryYearRequest.FromString,
                    response_serializer=prize__pb2.LaureatesResponse.SerializeToString,
            ),
            'GetLaureatesByKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByKeyword,
                    request_deserializer=prize__pb2.KeywordRequest.FromString,
                    response_serializer=prize__pb2.LaureatesResponse.SerializeToString,
            ),
            'GetLaureateByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateByName,
                    request_deserializer=prize__pb2.NameRequest.FromString,
                    response_serializer=prize__pb2.LaureateDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NobelPrizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NobelPrizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelPrizeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLaureatesByCategoryAndYearRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NobelPrizeService/GetLaureatesByCategoryAndYearRange',
            prize__pb2.CategoryYearRequest.SerializeToString,
            prize__pb2.LaureatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureatesByKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NobelPrizeService/GetLaureatesByKeyword',
            prize__pb2.KeywordRequest.SerializeToString,
            prize__pb2.LaureatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NobelPrizeService/GetLaureateByName',
            prize__pb2.NameRequest.SerializeToString,
            prize__pb2.LaureateDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
