# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prize.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'prize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprize.proto\"M\n\x13\x43\x61tegoryYearRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"4\n\x0bNameRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\",\n\x11LaureatesResponse\x12\x17\n\x0ftotal_laureates\x18\x01 \x01(\x05\"M\n\x17LaureateDetailsResponse\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t2\xde\x01\n\x11NobelPrizeService\x12N\n\"GetLaureatesByCategoryAndYearRange\x12\x14.CategoryYearRequest\x1a\x12.LaureatesResponse\x12<\n\x15GetLaureatesByKeyword\x12\x0f.KeywordRequest\x1a\x12.LaureatesResponse\x12;\n\x11GetLaureateByName\x12\x0c.NameRequest\x1a\x18.LaureateDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYYEARREQUEST']._serialized_start=15
  _globals['_CATEGORYYEARREQUEST']._serialized_end=92
  _globals['_KEYWORDREQUEST']._serialized_start=94
  _globals['_KEYWORDREQUEST']._serialized_end=127
  _globals['_NAMEREQUEST']._serialized_start=129
  _globals['_NAMEREQUEST']._serialized_end=181
  _globals['_LAUREATESRESPONSE']._serialized_start=183
  _globals['_LAUREATESRESPONSE']._serialized_end=227
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_start=229
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_end=306
  _globals['_NOBELPRIZESERVICE']._serialized_start=309
  _globals['_NOBELPRIZESERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
